package workflow.db;

// Generated 2014-5-15 19:06:46 by Hibernate Tools 3.4.0.CR1

/**
 * Webservicenodes generated by hbm2java
 */
public class Webservicenodes implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2806773806427347480L;
	private long wsId;
	private byte[] wsNodes;

	public Webservicenodes() {
	}

	public Webservicenodes(long wsId) {
		this.wsId = wsId;
	}

	public Webservicenodes(long wsId, byte[] wsNodes) {
		this.wsId = wsId;
		this.wsNodes = wsNodes;
	}

	public long getWsId() {
		return this.wsId;
	}

	public void setWsId(long wsId) {
		this.wsId = wsId;
	}

	public byte[] getWsNodes() {
		return this.wsNodes;
	}

	public void setWsNodes(byte[] wsNodes) {
		this.wsNodes = wsNodes;
	}

}
