package workflow.db;

// Generated 2014-5-15 19:06:46 by Hibernate Tools 3.4.0.CR1

/**
 * Workflows generated by hbm2java
 */
public class Workflows implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8420269351521910124L;
	private Long wfId;
	private String wfName;
	private String wfPath;

	public Workflows() {
	}

	public Workflows(String wfName, String wfPath) {
		this.wfName = wfName;
		this.wfPath = wfPath;
	}

	public Long getWfId() {
		return this.wfId;
	}

	public void setWfId(Long wfId) {
		this.wfId = wfId;
	}

	public String getWfName() {
		return this.wfName;
	}

	public void setWfName(String wfName) {
		this.wfName = wfName;
	}

	public String getWfPath() {
		return this.wfPath;
	}

	public void setWfPath(String wfPath) {
		this.wfPath = wfPath;
	}

}
