$(function(){
	$(".myMenu").buildMenu(
	{
		template:"menuVoices.html",
		additionalData:"pippo=1",
		menuWidth:160,
		openOnRight:false,
		menuSelector: ".menuContainer",
		containment:"wrapper",
		iconPath:"ico/",
		hasImages:true,
		fadeInTime:100,
		fadeOutTime:300,
		adjustLeft:2,
		minZindex:"auto",
		adjustTop:10,
		opacity:.95,
		shadow:true,
		closeOnMouseOut:true,
		closeAfter:1000
	});
});
