package workflow.db;

// Generated 2014-5-15 18:04:07 by Hibernate Tools 3.4.0.CR1

/**
 * Rating generated by hbm2java
 */
public class Rating implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4660387433839618722L;
	private Long rid;
	private Long userId;
	private Long wsId;
	private Float rateValue;

	public Rating() {
	}

	public Rating(Long userId, Long wsId, Float rateValue) {
		this.userId = userId;
		this.wsId = wsId;
		this.rateValue = rateValue;
	}

	public Long getRid() {
		return this.rid;
	}

	public void setRid(Long rid) {
		this.rid = rid;
	}

	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	public Long getWsId() {
		return this.wsId;
	}

	public void setWsId(Long wsId) {
		this.wsId = wsId;
	}

	public Float getRateValue() {
		return this.rateValue;
	}

	public void setRateValue(Float rateValue) {
		this.rateValue = rateValue;
	}

}
