package workflow.db;

// Generated 2014-5-15 19:06:46 by Hibernate Tools 3.4.0.CR1

/**
 * Webservices generated by hbm2java
 */
public class Webservices implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5916997427224707472L;
	private Long wsId;
	private String wsName;
	private String wsPath;

	public Webservices() {
	}

	public Webservices(String wsName, String wsPath) {
		this.wsName = wsName;
		this.wsPath = wsPath;
	}

	public Long getWsId() {
		return this.wsId;
	}

	public void setWsId(Long wsId) {
		this.wsId = wsId;
	}

	public String getWsName() {
		return this.wsName;
	}

	public void setWsName(String wsName) {
		this.wsName = wsName;
	}

	public String getWsPath() {
		return this.wsPath;
	}

	public void setWsPath(String wsPath) {
		this.wsPath = wsPath;
	}

}
