package workflow.db;

// Generated 2014-5-15 19:06:46 by Hibernate Tools 3.4.0.CR1

/**
 * Workflownodes generated by hbm2java
 */
public class Workflownodes implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6488037256001226747L;
	private long wfId;
	private byte[] wfNodes;

	public Workflownodes() {
	}

	public Workflownodes(long wfId) {
		this.wfId = wfId;
	}

	public Workflownodes(long wfId, byte[] wfNodes) {
		this.wfId = wfId;
		this.wfNodes = wfNodes;
	}

	public long getWfId() {
		return this.wfId;
	}

	public void setWfId(long wfId) {
		this.wfId = wfId;
	}

	public byte[] getWfNodes() {
		return this.wfNodes;
	}

	public void setWfNodes(byte[] wfNodes) {
		this.wfNodes = wfNodes;
	}

}
